version: "3.7"
volumes:
    pgdata:
        driver: local
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./bot/db/install.sql:/docker-entrypoint-initdb.d/install.sql
      - ./bot/db/update.sql:/docker-entrypoint-initdb.d/update.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bot
      - POSTGRES_INITDB_ARGS="-E utf8"
    shm_size: 8192MB
    security_opt:
      - seccomp:unconfined
  bot:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot
    volumes:
      - /var/log/hexlet/:/var/log/hexlet
    restart: always
    security_opt:
      - seccomp:unconfined
