[tool.poetry]
name = "hexlet_bot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Telethon = "^1.22.0"
yml = "^0.0.1"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
