bot_config:
  report_day: 2  # tuesday
  sleep_time: 60

db:
  user: bot
  name: bot
  password: 123
  host: localhost
  port: 5432


logging:
#  filename: /var/log/bot/bot.log
  format: "{asctime} {levelname:5} {name}: {message}"
  level: INFO
  loggers:
    bot: DEBUG
