# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start DB
      run: docker-compose up -d db
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install poetry
    - name: Build package
      run: |
        make build
    - name:  Install package
      run: |
        make install
    - name:  Test run
      run: |
        make test
    - name:  Coverage report
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 35f0bf1c2aedcd6149e645987e1ac3f3040dac00e0ecf21a703d38d106c13abc
      with:
        coverageCommand: make coverage
